name: save_bite
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  #bloc for state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.2
  # Functional programming thing
  dartz: ^0.10.1
  # Value Equality
  equatable: ^2.0.7
  #Service Locator
  get_it: ^8.0.2
  #Remote Api
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.2
  #Local cache
  shared_preferences: ^2.0.15

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Noto Scans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils
  filename: app_assets.dart
  field_prefix: null
