name: save_bite
description: "A Flutter app for reducing food waste through AI-powered
  recommendations and inventory management."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.2
  go_router: ^14.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.2.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.5
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Noto Scans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
